### ISSUE TITLE
warning

### ISSUE THREAD

**Issue by HaoziBlack** [greek-zzf/crawler#10]
i don't like sina , what about Baidu?

**Comment by greek-zzf** [comment]
Maybe it can be done when I am stronger

**Comment by greek-zzf** [comment]
> i don't like sina , what about Baidu?
Maybe it can be done when I am stronger

**Comment by greek-zzf** [comment]
百度等大型网站都有非常优秀的反爬机制，目前我也是做不到的，爬爬小网站还是可以的

**Comment by HaoziBlack** [comment]
### 你就是看不起新浪咯 ###
